### ISSUE TITLE
persist doesn't work

### ISSUE THREAD

**Issue by 72squared** [yinqiwen/ardb#276]
All commands are run within a second or two of each other. Here is how ardb works:

```
127.0.0.1:16379> set foo bar
OK
127.0.0.1:16379> get foo
"bar"
127.0.0.1:16379> expire foo 30
(integer) 1
127.0.0.1:16379> get foo
"bar"
127.0.0.1:16379> persist foo
(integer) 0
127.0.0.1:16379> get foo
(nil)
127.0.0.1:16379> 
```

I would expect persist would clear any expiry. Instead it seems to clear the key.

Here is how redis behaves:
```
127.0.0.1:6379> set foo bar
OK
127.0.0.1:6379> get foo
"bar"
127.0.0.1:6379> expire foo 30
(integer) 1
127.0.0.1:6379> get foo
"bar"
127.0.0.1:6379> persist foo
(integer) 1
127.0.0.1:6379> get foo
"bar"
127.0.0.1:6379> 
```

**Comment by yinqiwen** [comment]
sorry, this issue is introduce by the fix for issue #275,  fixed by latest commit.

**Comment by 72squared** [comment]
okay that issue is fixed, now one more that is closely related. 

Here is ardb:
```
127.0.0.1:16379> set foo bar
OK
127.0.0.1:16379> get foo
"bar"
127.0.0.1:16379> ttl foo
(integer) 0
127.0.0.1:16379> 
```

Here is redis:
```
127.0.0.1:6379> set foo bar
OK
127.0.0.1:6379> get foo
"bar"
127.0.0.1:6379> ttl foo
(integer) -1
127.0.0.1:6379> 
```

It seems if no ttl is set on a key, you return -1.

http://redis.io/commands/ttl

"Starting with Redis 2.8 the return value in case of error changed:
The command returns -2 if the key does not exist.
The command returns -1 if the key exists but has no associated expire."

**Comment by yinqiwen** [comment]
fixed.

**Comment by 72squared** [comment]
okay, looks good. I have 3 more unit tests still failing out of 426 in my application but it's something subtle so I need to trace down the root cause.
